"""Single-call HTML QC dashboard composer (bokeh-based).

Composes all the metrics + plots from :mod:`alphaphos.qc.metrics` and
:mod:`alphaphos.qc.plots` into a single HTML file that can be emailed,
archived, or browsed standalone.

Usage:

.. code-block:: python

    from alphaphos.qc import generate_dashboard

    generate_dashboard(
        adata,
        output_path="qc.html",
        psm_df=raw_psm,                 # optional, enables §4 contam panel
        impute_audit=audit_df,          # optional, enables §5 imputation panel
        title="EGF nanoPhos · 2026-05-27",
    )
"""

from __future__ import annotations

import datetime as _dt
from pathlib import Path
from typing import TYPE_CHECKING

import pandas as pd
from bokeh.embed import file_html
from bokeh.layouts import column, row
from bokeh.models import Div
from bokeh.resources import INLINE

from alphaphos.qc.metrics import (
    compute_classI_comparison,
    compute_contaminant_breakdown,
    compute_imputation_summary,
    compute_localization_distribution,
    compute_missingness,
    compute_multiplicity_distribution,
    compute_n_classI_per_sample,
    compute_per_condition_cv_by_aa,
    compute_pipeline_waterfall,
    compute_replicate_correlation,
    compute_sample_dendrogram_order,
    compute_sty_ratio,
)
from alphaphos.qc.plots import (
    plot_classI_comparison,
    plot_contaminant_breakdown,
    plot_imputation_summary,
    plot_localization_distribution,
    plot_missingness,
    plot_multiplicity,
    plot_n_classI,
    plot_per_condition_cv_by_aa,
    plot_pipeline_waterfall,
    plot_replicate_correlation,
    plot_sty_ratio,
)

if TYPE_CHECKING:
    import anndata as ad


def _section_header(title: str) -> Div:
    return Div(
        text=f'<h2 style="margin-top:24px;margin-bottom:8px;'
        f'border-bottom:1px solid #ccc;padding-bottom:4px;">{title}</h2>',
        width=1200,
    )


def _format_pipeline_params_html(params: dict) -> str:
    """Render the pipeline_params dict as a bullet list."""
    if not params:
        return "<p><em>No pipeline params recorded.</em></p>"
    items = []
    for k, v in sorted(params.items()):
        items.append(f"<li><code>{k}</code> = {v!r}</li>")
    return "<ul style='font-family:monospace;font-size:11pt;'>" + "".join(items) + "</ul>"


def generate_dashboard(
    adata: ad.AnnData,
    output_path: str | Path,
    *,
    psm_df: pd.DataFrame | None = None,
    impute_audit: pd.DataFrame | None = None,
    title: str | None = None,
    classI_cutoff: float = 0.75,
) -> Path:
    """Build a single-file HTML QC dashboard from an alphaPhos AnnData.

    Parameters
    ----------
    adata
        The post-pipeline AnnData (output of ``to_anndata`` + downstream
        steps). The richer the metadata in ``var`` / ``layers`` / ``uns``,
        the more panels light up.
    output_path
        Path to write the HTML to (e.g. ``"qc.html"``). Parent directory
        is created if missing.
    psm_df
        Optional raw PSM-level DataFrame (from
        ``read_psm(..., drop_contaminants=False)``). When provided, the
        contaminant breakdown panel is rendered.
    impute_audit
        Optional audit DataFrame from
        ``impute_hybrid(..., return_audit=True)``. When provided, the
        imputation MAR/MNAR breakdown panel is rendered.
    title
        Dashboard title. Defaults to a generated string with the adata
        shape + timestamp.
    classI_cutoff
        Cutoff used by the Class I diagnostics panel. Default 0.75.

    Returns
    -------
    Path
        The path to the written HTML file.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    timestamp = _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    version = adata.uns.get("alphaphos", {}).get("version", "?")
    if title is None:
        title = f"alphaPhos QC | {adata.n_obs} samples x {adata.n_vars:,} sites | {timestamp}"

    header = Div(
        text=(
            f'<h1 style="margin-bottom:4px;">{title}</h1>'
            f'<p style="color:#666;margin-top:0;">'
            f"Generated by alphaPhos {version} · adata: {adata.shape} · "
            f"obs cols: {list(adata.obs.columns)} · var cols: {len(adata.var.columns)}"
            f"</p>"
        ),
        width=1200,
    )

    # §1 — Pipeline waterfall
    waterfall_df = compute_pipeline_waterfall(adata)
    s1 = column(_section_header("§1 Pipeline waterfall"), plot_pipeline_waterfall(waterfall_df))

    # §2 — Sample QC grid (2x3)
    sty_df = compute_sty_ratio(adata)
    loc_df = compute_localization_distribution(adata)
    mult_df = compute_multiplicity_distribution(adata)
    miss_df = compute_missingness(adata)
    nci_df = compute_n_classI_per_sample(adata, classI_cutoff=classI_cutoff)
    cv_df = compute_per_condition_cv_by_aa(adata)

    s2 = column(
        _section_header("§2 Sample-level QC"),
        row(plot_sty_ratio(sty_df), plot_localization_distribution(loc_df)),
        row(plot_multiplicity(mult_df), plot_missingness(miss_df)),
        row(plot_n_classI(nci_df), plot_per_condition_cv_by_aa(cv_df)),
    )

    # §3 — Reproducibility (correlation + dendrogram-ordered)
    corr_df = compute_replicate_correlation(adata)
    sample_order = compute_sample_dendrogram_order(adata)
    s3 = column(
        _section_header("§3 Reproducibility"),
        plot_replicate_correlation(corr_df, sample_order=sample_order),
    )

    # §4 — Class I + contaminant
    classI_df = compute_classI_comparison(adata, classI_cutoff=classI_cutoff)
    contam_df = (
        compute_contaminant_breakdown(psm_df)
        if psm_df is not None
        else pd.DataFrame(columns=["gene", "n_rows"])
    )
    s4 = column(
        _section_header("§4 Class I + contaminant diagnostics"),
        row(plot_classI_comparison(classI_df), plot_contaminant_breakdown(contam_df)),
    )

    # §5 — Imputation diagnostics
    imp_df = (
        compute_imputation_summary(impute_audit)
        if impute_audit is not None
        else pd.DataFrame(columns=["sample_idx", "strategy", "n"])
    )
    s5 = column(
        _section_header("§5 Imputation diagnostics"),
        plot_imputation_summary(imp_df),
    )

    # §6 — Provenance (pipeline params table)
    pp = adata.uns.get("alphaphos", {}).get("pipeline_params", {})
    s6 = column(
        _section_header("§6 Pipeline parameters"),
        Div(text=_format_pipeline_params_html(pp), width=1200),
    )

    layout = column(header, s1, s2, s3, s4, s5, s6)
    html = file_html(layout, resources=INLINE, title=title)
    output_path.write_text(html, encoding="utf-8")
    return output_path
